---
- name: download nodesource key
  # https does not work on centos-5
  command: >
    wget -O /root/68576280.gpg
    https://deb.nodesource.com/gpgkey/nodesource.gpg.key
  args:
    creates: /root/68576280.gpg
  sudo: yes
